package com.anandbibek.web.notifications.ui.theme

import androidx.compose.ui.graphics.Color

// Generate them via theme builder
// https://material-foundation.github.io/material-theme-builder/#/custom

val webLightPrimary = Color(0xFF825500)
val webLightOnPrimary = Color(0xFFFFFFFF)
val webLightPrimaryContainer = Color(0xFFFFDDAE)
val webLightOnPrimaryContainer = Color(0xFF2A1800)
val webLightSecondary = Color(0xFF6F5B40)
val webLightOnSecondary = Color(0xFFFFFFFF)
val webLightSecondaryContainer = Color(0xFFFADEBC)
val webLightOnSecondaryContainer = Color(0xFF271904)
val webLightTertiary = Color(0xFF516440)
val webLightOnTertiary = Color(0xFFFFFFFF)
val webLightTertiaryContainer = Color(0xFFD3EABC)
val webLightOnTertiaryContainer = Color(0xFF102004)
val webLightError = Color(0xFFBA1B1B)
val webLightErrorContainer = Color(0xFFFFDAD4)
val webLightOnError = Color(0xFFFFFFFF)
val webLightOnErrorContainer = Color(0xFF410001)
val webLightBackground = Color(0xFFFCFCFC)
val webLightOnBackground = Color(0xFF1F1B16)
val webLightSurface = Color(0xFFFCFCFC)
val webLightOnSurface = Color(0xFF1F1B16)
val webLightSurfaceVariant = Color(0xFFF0E0CF)
val webLightOnSurfaceVariant = Color(0xFF4F4539)
val webLightOutline = Color(0xFF817567)
val webLightInverseOnSurface = Color(0xFFF9EFE6)
val webLightInverseSurface = Color(0xFF34302A)
val webLightPrimaryInverse = Color(0xFFFFB945)

val webDarkPrimary = Color(0xFFFFB945)
val webDarkOnPrimary = Color(0xFF452B00)
val webDarkPrimaryContainer = Color(0xFF624000)
val webDarkOnPrimaryContainer = Color(0xFFFFDDAE)
val webDarkSecondary = Color(0xFFDDC3A2)
val webDarkOnSecondary = Color(0xFF3E2E16)
val webDarkSecondaryContainer = Color(0xFF56442B)
val webDarkOnSecondaryContainer = Color(0xFFFADEBC)
val webDarkTertiary = Color(0xFFB8CEA2)
val webDarkOnTertiary = Color(0xFF243516)
val webDarkTertiaryContainer = Color(0xFF3A4C2B)
val webDarkOnTertiaryContainer = Color(0xFFD3EABC)
val webDarkError = Color(0xFFFFB4A9)
val webDarkErrorContainer = Color(0xFF930006)
val webDarkOnError = Color(0xFF680003)
val webDarkOnErrorContainer = Color(0xFFFFDAD4)
val webDarkBackground = Color(0xFF1F1B16)
val webDarkOnBackground = Color(0xFFEAE1D9)
val webDarkSurface = Color(0xFF1F1B16)
val webDarkOnSurface = Color(0xFFEAE1D9)
val webDarkSurfaceVariant = Color(0xFF4F4539)
val webDarkOnSurfaceVariant = Color(0xFFD3C4B4)
val webDarkOutline = Color(0xFF9C8F80)
val webDarkInverseOnSurface = Color(0xFF32281A)
val webDarkInverseSurface = Color(0xFFEAE1D9)
val webDarkPrimaryInverse = Color(0xFF624000)